# Generated by Django 4.2.22 on 2025-06-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='manifesto',
            field=models.TextField(blank=True),
        ),
    ]
