# Generated by Django 4.2.22 on 2025-06-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
